# Generated by Django 5.2.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_content', models.FloatField(help_text='Nitrogen content in soil')),
                ('p_content', models.FloatField(help_text='Phosphorus content in soil')),
                ('k_content', models.FloatField(help_text='Potassium content in soil')),
                ('ph', models.FloatField(help_text='Soil pH level')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('latitude', models.FloatField(blank=True, help_text='Location latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Location longitude', null=True)),
                ('predicted_crop', models.CharField(help_text='Recommended crop', max_length=100)),
                ('confidence_score', models.FloatField(help_text='Model confidence score')),
                ('alternative_crops', models.JSONField(default=list, help_text='Alternative crop suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('test_samples', models.IntegerField()),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]