# Generated by Django 5.2.4 on 2025-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_slots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
