# Generated by Django 5.2.4 on 2025-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crops',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
