# Generated by Django 5.2.4 on 2025-11-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0006_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
